.TH "EncoderUtil" 3 "Sun Oct 13 2019" "Version 0.0.5" "VEX-2019 Team Convergence" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EncoderUtil
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <EncoderUtil\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static double \fBgetInches\fP (int ticks, double wheelDiameter)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Class that helps with Encoder math 
.PP
Definition at line 8 of file EncoderUtil\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "static double EncoderUtil::getInches (int ticks, double wheelDiameter)\fC [static]\fP"
Gets ticks from encoder 
.PP
\fBParameters\fP
.RS 4
\fIticks\fP The current number of ticks of ENCODER 
.br
\fIwheelDiameter\fP Diameter of wheel 
.RE
.PP
\fBReturns\fP
.RS 4
Get the distance in inches 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for VEX-2019 Team Convergence from the source code\&.
