.TH "C:/Users/kidco/VEX-2019/include/User/MoveTrayCommand.h" 3 "Sun Oct 13 2019" "Version 0.0.5" "VEX-2019 Team Convergence" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/kidco/VEX-2019/include/User/MoveTrayCommand.h
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./main\&.h'\fP
.br
\fC#include 'Command\&.h'\fP
.br
\fC#include 'TraySubsystem\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMoveTrayCommand\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VEX-2019 Team Convergence from the source code\&.
